---
- hosts: cluster
  vars:
    ansible_python_interpreter: /usr/bin/python3
  pre_tasks:
  - service_facts:
    register: svc_list
    tags: always
  # - set_vars:
  #     hosts_inventory: "{{ vars.hostvars }}"

  tasks:
  - name: Install gotop
    unarchive:
      src: https://github.com/xxxserxxx/gotop/releases/download/v4.1.1/gotop_v4.1.1_linux_amd64.tgz
      dest: /usr/local/bin
      remote_src: yes
  - name: Backup home to s3
    cron:
      name: Backup home to s3
      job: '/bin/bash -lc "s3cmd sync /home/ s3://vultr-{{ env }}/{{ ansible_fqdn }}/home/" 2>&1'
      minute: "30"
      state: absent
    tags:
    - backup
  - name: Backup volumes to s3
    cron:
      name: Backup volumes to s3
      job: '/bin/bash -lc "s3cmd sync /var/lib/docker/volumes/ s3://vultr-{{ env }}/{{ ansible_fqdn }}/home/" 2>&1'
      minute: "05"
      state: absent
    tags: backup
  - name: Install loki plugin to docker
    shell: "docker plugin install grafana/loki-docker-driver:latest --alias loki --grant-all-permissions; exit 0"
  
  roles:
  - role: core
    tags:
    - core
    - base
  - role: users
    tags:
    - users
    - base
  - role: node_exporter
    tags:
    - monitoring
    - node-exporter
#  - role: promtail
#    tags:
#    - monitoring
#    - promtail
  - role: docker-ce
    tags:
    - docker
  - role: restic
    tags:
    - backup
    - restic
  - role: s3cmd
    tags:
    - backup

- name: "{{ env }} - Configure nomad"
  include: nomad.yml
