---
- hosts: localhost
  gather_facts: no
  tasks:
  # --------------  Prepare Firewalls  -------------- #
  - name: "{{ env }} - Init MASTERS firewall"
    vultr_firewall_group:
      name: "{{ env }}_MASTERS"
  - name: "{{ env }} - Create FW rules"
    vultr_firewall_rule:
      group: "{{ env }}_MASTERS"
      protocol: "{{ item.proto }}"
      port: "{{ item.port }}"
      cidr: "{{ item.cidr }}"
    with_items:
    # Allow http
    - port: 80
      cidr: "0.0.0.0/0"
      proto: tcp
    # Allow https
    - port: 443
      cidr: "0.0.0.0/0"
      proto: tcp
    # SSH port
    - port: 22
      cidr: "0.0.0.0/0"
      proto: tcp
    # Nomad mgmt
    - port: 4646
      cidr: "0.0.0.0/0"
      proto: tcp

  - name: "{{ env }} - Init NODES firewall"
    vultr_firewall_group:
      name: "{{ env }}_NODES"
  - name: "{{ env }} - Cretate NODES rules"
    vultr_firewall_rule:
      group: "{{ env }}_NODES"
      protocol: "{{ item.proto }}"
      port: "{{ item.port }}"
      cidr: "{{ item.cidr }}"
    with_items:
    # Allow http
    - port: 80
      cidr: "0.0.0.0/0"
      proto: tcp
    # Allow https
    - port: 433
      cidr: "0.0.0.0/0"
      proto: tcp
    # SSH port
    - port: 22
      cidr: "0.0.0.0/0"
      proto: tcp

- hosts: cluster
  gather_facts: no
  pre_tasks:
  - name: "{{ env }} - Cloud members are running"
    local_action:
      module: vultr_server
      name: "{{ inventory_hostname_short }}"
      os: "Debian 10 x64 (buster)"
      private_network_enabled: yes
      plan: "{{ plan }}"
      ssh_keys:
      - marek
#      - github
#      - "{{ root_keys }}"
      firewall_group: "{{ firewall_grp }}"
      region: "{{ region }}"
      state: present

- hosts: localhost
  tasks:
#  - debug:
#      msg: "{{ env }} - {{ item }} IN A {{ hostvars[item].v4_main_ip }}"
#    with_items: "{{ groups['all'] }}"
  - name: "{{ env }} - Register public domains"
    cloudflare_dns:
      zone: "fejk.net"
      record: "{{ item }}"
      type: A
      proxied: no
      value: "{{ hostvars[item].v4_main_ip }}"
      state: present
      solo: true
      account_email: "{{ cloudflare_account_email }}"
      account_api_token: "{{ cloudflare_account_api_token }}"
    with_items: "{{ groups['cluster'] }}"
  - name: "{{ env }} - Allow all TCP betwean nodes"
    vultr_firewall_rule:
      group: "{{ env }}_MASTERS"
      protocol: tcp
      start_port: 1
      end_port: 65535
      cidr: "{{ hostvars[item].v4_main_ip }}/32"
    with_items: "{{ groups['cluster'] }}"
  - name: "{{ env }} - Allow all UDP betwean nodes"
    vultr_firewall_rule:
      group: "{{ env }}_MASTERS"
      protocol: udp
      start_port: 1
      end_port: 65535
      cidr: "{{ hostvars[item].v4_main_ip }}/32"
    with_items: "{{ groups['cluster'] }}"
  - name: "{{ env }} - Allow all TCP betwean nodes"
    vultr_firewall_rule:
      group: "{{ env }}_NODES"
      protocol: tcp
      start_port: 1
      end_port: 65535
      cidr: "{{ hostvars[item].v4_main_ip }}/32"
    with_items: "{{ groups['cluster'] }}"
  - name: "{{ env }} - Allow all UDP betwean nodes"
    vultr_firewall_rule:
      group: "{{ env }}_NODES"
      protocol: udp
      start_port: 1
      end_port: 65535
      cidr: "{{ hostvars[item].v4_main_ip }}/32"
    with_items: "{{ groups['cluster'] }}"


- name: "{{ env }} - Configure base servers"
  include: deploy.yml
