---
- name: Manage vultr keys
  hosts: localhost
  tasks:
  - name: ensure an SSH key is present
    ngine_io.vultr.vultr_ssh_key:
      name: marek
      ssh_key: "{{ lookup('file', 'keys/marek') }}"
