---
- hosts: cluster
  roles:
  - role: nomad
    tags:
    - nomad
  - role: nomad-cni
    tags:
    - cni
    - nomad
  - role: consul
    tags:
    - consul

- import_playbook: nomad-configure.yml
