---
- hosts: cluster
  roles:
  - role: nomad
    tags:
    - nomad

  - role: nomad-cni
    tags:
    - cni
    - nomad

  # Since 1.4.3 the Nomad cluster can run 
  # without the consul
  #
  # - role: consul
  #   tags:
  #   - consul

- import_playbook: nomad-configure.yml
