docker_daemon_options:
  debug: false
  experimental: true
  
  # !!! Don't stop running containers during updates !!!
  # in some cases a default FIFO log size (64K) is not enought so increase 
  # the size there /proc/sys/fs/pipe-max-size
  live-restore: true

  # default log driver will be loki
#  log-driver: "loki"
#  log-opts:
#    loki-url: "https://localhost:3100/loki/api/v1/push"
#    loki-batch-size: "100"
#    max-file: "3"
#    max-size: "10m"
  
  # Enable prometheus metrics endpoint
  metrics-addr: "127.0.0.1:9323"
