---
node_exporter_web_telemetry_path: /metrics
node_exporter_textfile_dir: /tmp/metrics

node_exporter_disabled_collectors:
- infiniband
- bonding
- nfs
- mdadm
- nfsd
- powersupplyclass
- rapl
- zfs
- xfs

node_exporter_enabled_collectors:
- systemd
- processes
- textfile:
    directory: "{{ node_exporter_textfile_dir }}"
