prometheus_version: "2.26.0"
prometheus_db_dir: "/home/prometheus"
prometheus_master_protect_home: false
prometheus_storage_retention: "10d"
prometheus_web_listen_address: "0.0.0.0:9090"
prometheus_web_external_url: ""

prometheus_scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
    - targets:
      - localhost:9090

  - job_name: node_exporter
    metrics_path: /metrics
    static_configs:
    - targets:
      - localhost:9100

  - job_name: nginx_exporter
    static_configs:
    - targets:
      - 0.0.0.0:9113
