docker_daemon_settings:
  debug: false
  experimental: true
  
  # !!! Don't stop running containers during updates !!!
  # in some cases a default FIFO log size (64K) is not enought so increase 
  # the size there /proc/sys/fs/pipe-max-size
  live-restore: true

  # default log driver will be loki
  log-driver: "loki"
  log-opts:
    loki-url: "http://loki.fejk.net/loki/api/v1/push"
    loki-batch-size: "400"
    max-file: "3"
    max-size: "10m"
  
  # Enable prometheus metrics endpoint
  metrics-addr: "127.0.0.1:9323"
