---
global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "node-exporter"
    basic_auth:
      username: agent
      password_file: "/local/node_exporter_password.sec"
    metrics_path: "/metrics"
    scrape_interval: "30s"
    static_configs:
    # PROD nodes
    - targets:
        - "n1.fejk.net:9100"
        - "n2.fejk.net:9100"

      labels:
        env: prod

#   - job_name: 'traefik'
#     consul_sd_configs:
#     - server: '172.17.0.1:8500'
# #      token: 
#       services: ['traefik']

#    relabel_configs:
#    - source_labels: ['__meta_consul_service_port']
#      target_label:  '__meta_consul_service_port'
#      replacement:   '8081'
#    metrics_path: /metrics


  - job_name: 'nomad_apps'
    nomad_sd_configs:
    - server: 'http://n1.fejk.net:4646'
      authorization:
        credentials_file: '/local/nomad_token.sec'
      allow_stale: true
      follow_redirects: true
      refresh_interval: 1m
      enable_http2: true
      # namespace: default
      # region: global

    scrape_interval: 15s
    scrape_timeout: 5s
    scheme: http
    tls_config:
      insecure_skip_verify: true
    follow_redirects: true
    enable_http2: true
    relabel_configs:
    - source_labels: [__meta_nomad_tags]
      regex: .*,metrics=true,.*
      action: keep
    - source_labels: [__meta_nomad_tags]
      separator: ','
      regex: .*,metrics.path=(.[a-z\/\_0-9]*),(.*)
      replacement: '${1}'
      target_label: __metrics_path__
    - replacement: "prod-cluster"
      target_label: cluster
    - replacement: "prod"
      target_label: env
    - source_labels: [__meta_nomad_service]
      regex: (.*)
      replacement: "nomad-${1}"
      target_label: job



  - job_name: 'prometheus'
    metrics_path: "/metrics"
    scrape_interval: "30s"
    static_configs:
    # PROD nodes
    - targets:
        - "127.0.0.1:9090"
      labels:
        env: prod


